version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana Admin password
    networks:
      - monitoring

  server-monitor:
    image: your_flask_image  # Replace this with the Flask app image name or use a build context
    container_name: server-monitor
    ports:
      - "5000:5000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
