version: '3'

services:
prometheus:
image: prom/prometheus
container_name: prometheus
ports:
- "9090:9090"
volumes:
- ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
networks:
- monitoring
restart: always
depends_on:
- server-monitor
healthcheck:
test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/healthy"]
interval: 30s
timeout: 10s
retries: 3

grafana:
image: grafana/grafana
container_name: grafana
ports:
- "3000:3000"
environment:
- GF_SECURITY_ADMIN_PASSWORD=admin
networks:
- monitoring
restart: always
depends_on:
- prometheus
healthcheck:
test: ["CMD", "wget", "-qO-", "http://localhost:3000/login"]
interval: 30s
timeout: 10s
retries: 3

server-monitor:
image: your_flask_image
container_name: server-monitor
ports:
- "5000:5000"
networks:
- monitoring
restart: always
healthcheck:
test: ["CMD", "wget", "-qO-", "http://localhost:5000/metrics"]
interval: 30s
timeout: 10s
retries: 3

networks:
monitoring:
driver: bridge