global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flask_server_monitor"
    static_configs:
      - targets: ["server-monitor:5000"]
        labels:
          app: "flask_monitor"
          
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
